export const locations = [
  {
    name: "Riverwalk",
    address: "123 Main Street",
    city: "San Antonio",
    state: "TX",
    zipCode: "55555",
    daysOpen: "7 days a week",
    hoursOpen: "11am to 12am",
  },
  {
    name: "Galleria",
    address: "123 Shoppers Avenue",
    city: "Dallas",
    state: "TX",
    zipCode: "77777",
    daysOpen: "Monday - Friday",
    hoursOpen: "11am to 10pm",
  },
  {
    name: "Staples Center",
    address: "123 Sports Drive",
    city: "Los Angeles",
    state: "CA",
    zipCode: "99999",
    daysOpen: "Monday - Friday",
    hoursOpen: "11am to 10pm",
  },
  {
    name: "Millennium Park",
    address: "123 Park Avenue",
    city: "Chicago",
    state: "IL",
    zipCode: "44444",
    daysOpen: "Monday - Friday",
    hoursOpen: "11am to 10pm",
  },
];
